### ISSUE TITLE
AttributeError: module 'keras.utils.conv_utils' has no attribute 'normalize_data_format'

### ISSUE THREAD

**Issue by shliang0603** [deepfakes/faceswap#501]
## AttributeError: module 'keras.utils.conv_utils' has no attribute 'normalize_data_format'
When I train the model reproting the error, but I can't find the right solution.

Using TensorFlow backend.
Model A Directory: input_A
Model B Directory: input_B
Training data directory: models
Loading data, this may take a while...
Starting. Press 'ENTER' to stop training and save model
Loading Model from Model_Original plugin...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Anaconda_install\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Anaconda_install\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "E:\MagicP\2_StartAndEnd_CodeAndDataset\10_deepfakes\faceswap-master\scripts\train.py", line 97, in process_thread
    raise err
  File "E:\MagicP\2_StartAndEnd_CodeAndDataset\10_deepfakes\faceswap-master\scripts\train.py", line 86, in process_thread
    model = self.load_model()
  File "E:\MagicP\2_StartAndEnd_CodeAndDataset\10_deepfakes\faceswap-master\scripts\train.py", line 102, in load_model
    model = PluginLoader.get_model(self.trainer_name)(model_dir, self.args.gpus)
  File "E:\MagicP\2_StartAndEnd_CodeAndDataset\10_deepfakes\faceswap-master\plugins\Model_Original\AutoEncoder.py", line 17, in __init__
    self.encoder = self.Encoder()
  File "E:\MagicP\2_StartAndEnd_CodeAndDataset\10_deepfakes\faceswap-master\plugins\Model_Original\Model.py", line 61, in Encoder
    x = self.upscale(512)(x)
  File "E:\MagicP\2_StartAndEnd_CodeAndDataset\10_deepfakes\faceswap-master\plugins\Model_Original\Model.py", line 47, in block
    x = PixelShuffler()(x)
  File "E:\MagicP\2_StartAndEnd_CodeAndDataset\10_deepfakes\faceswap-master\lib\PixelShuffler.py", line 13, in __init__
    self.data_format = conv_utils.normalize_data_format(data_format)
AttributeError: module 'keras.utils.conv_utils' has no attribute 'normalize_data_format'

**Comment by gessyoo** [comment]
I think the latest version keras version, 2.2 is incompatible with keras-contrib 2.08, see https://stackoverflow.com/questions/51652690/importerror-cannot-import-name-normalize-data-format.  Try running: pip install --upgrade keras==2.1.6 and pip install --upgrade keras-contrib==2.08.

**Comment by torzdf** [comment]
We don't use keras-contrib.

Faceswap is confirmed working on keras 2.2.0 (as per requirements.txt). Cannot vouch for 2.2.1

**Comment by shliang0603** [comment]
@gessyoo Thanks for your answering

**Comment by shliang0603** [comment]
@torzdf Thanks for your answering . I upgrade the keras version form 2.2.1 to 2.2.0, now , it can  work well.
