### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'BytesLimit' in binary running on DESKTOP-XXX Make sure the Op and Kernel are registered in the binary running in this process.

### ISSUE THREAD

**Issue by ruah1984** [deepfakes/faceswap#540]
is it keras version issue again or tensorflow

**Comment by torzdf** [comment]
More info please

**Comment by ruah1984** [comment]
Latest pull, using faceswap.py gui extract

Loading...
Output Directory: D:\data_dst\aligned
Input Directory: D:\data_dst
Loading Detect from Mtcnn plugin...
Loading Align from Fan plugin...

NB: Parallel processing disabled.
You may get faster extraction speeds by enabling it with the -mp switch

Starting, this may take a while...
Initializing MTCNN Detector...Process SpawnProcess-2:

Traceback (most recent call last):
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
self.run()
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\ruah1\Downloads\faceswap-master (3)\faceswap-master\plugins\extract\detect\mtcnn.py", line 100, in detect_faces
super().detect_faces(*args, **kwargs)
File "C:\Users\ruah1\Downloads\faceswap-master (3)\faceswap-master\plugins\extract\detect\_base.py", line 80, in detect_faces
self.initialize(*args, **kwargs)
File "C:\Users\ruah1\Downloads\faceswap-master (3)\faceswap-master\plugins\extract\detect\mtcnn.py", line 73, in initialize
alloc = int(sess.run(tf.contrib.memory_stats.BytesLimit()) /
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\memory_stats\python\ops\memory_stats_ops.py", line 36, in BytesLimit
return gen_memory_stats_ops.bytes_limit()
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\memory_stats\ops\gen_memory_stats_ops.py", line 64, in bytes_limit
"BytesLimit", name=name)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
op_def=op_def)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3162, in create_op
compute_device=compute_device)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3208, in _create_op_helper
set_shapes_for_outputs(op)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2427, in set_shapes_for_outputs
return _set_shapes_for_outputs(op)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2400, in _set_shapes_for_outputs
shapes = shape_func(op)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2330, in call_with_requiring
return call_cpp_shape_fn(op, require_shape_fn=True)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
require_shape_fn)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
input_tensors_as_shapes, status)
File "C:\Users\ruah1\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'BytesLimit' in binary running on DESKTOP-3J7UVPN. Make sure the Op and Kernel are registered in the binary running in this process.
Terminating Process...
Terminated
Process exited.

**Comment by torzdf** [comment]
What TF version?

**Comment by ruah1984** [comment]
Name: tensorflow
Version: 1.5.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: c:\users\ruah1\appdata\local\programs\python\python36\lib\site-packages
Requires: six, protobuf, wheel, absl-py, tensorflow-tensorboard, numpy
Required-by: keras-vggface

**Comment by torzdf** [comment]
Upgrade your Tensorflow. 1.12 should work fine

**Comment by ruah1984** [comment]
after upgrade to 1.12 it become below error

ImportError: cannot import name 'abs'

**Comment by torzdf** [comment]
Make sure you are on latest repo and your packages are up to date with latest requirements.txt

You can check out the (alpha) logging branch and provide a crash log if you are still having issues

**Comment by ruah1984** [comment]
found the same issue like what other facing before
[https://github.com/deepfakes/faceswap/issues/529
](url)

current tensorflow version is 1.12

**Comment by torzdf** [comment]
I'm not clear what your issue is. That issue was solved.

You're better off getting support on the Discord:
https://discord.gg/FdEwxXd
